# Generated by Django 4.2.4 on 2023-08-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category_account_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(default=None, max_length=1024, null=True)),
                ('invoice_nr', models.CharField(default=None, max_length=128, null=True)),
                ('is_commited', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_bookings', to='api.account')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_bookings', to='api.account')),
            ],
        ),
    ]
