# Generated by Django 4.2.4 on 2023-08-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='invoice_nr',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='text',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
